# Generated by Django 4.0.4 on 2022-05-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_customer_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, height_field='10px', upload_to='image/', width_field='10px'),
        ),
    ]
