# Generated by Django 4.0.4 on 2022-05-19 06:03

from django.db import migrations, models
import enroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='image/default.jpg', null=True, upload_to=enroll.models.customer.get_avatar_path),
        ),
    ]
